# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-02 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210402_1401'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
